# 1. 【必改】修改为你的 GitHub Pages 网址
baseurl      = "https://Meze628.github.io/"

# 2. 【必改】指定本地主题 (原文件缺了这行，导致无法找到主题)
theme        = "hugo-theme-stack"

# 3. 网站基础设置
languageCode = "zh-cn"
title        = "Meze's Bolg"  # 这里改成你想要的博客名称

# Theme i18n support
# 建议改为 zh-cn (简体中文)
defaultContentLanguage = "zh-cn"

# 4. 【必改】开启中文字数统计
# 设置为 true，否则中文文章的字数统计和阅读时间会不准确
hasCJKLanguage = true

# 评论系统设置 (暂时可以先不动，或者留空)
disqusShortname = "hugo-theme-stack"

[pagination]
    pagerSize = 5