[zh-cn]
    languageName = "中文"
    title = "Meze's Blog"
    subtitle = "这是我的技术博客"
    owner = "Meze"
    copyright = "Meze"

    [zh-cn.params]
        readMore = "阅读全文"
        date_format = "2006-01-02"
    
    # --- 1. 左侧主菜单 (Main Menu) ---
    [zh-cn.menu]
        [[zh-cn.menu.main]]
            identifier = "home"
            name = "首页"
            url = "/"
            weight = 1
            [zh-cn.menu.main.params]
                icon = "home"

        [[zh-cn.menu.main]]
            identifier = "archives"
            name = "归档"
            url = "/archives/"
            weight = 2
            [zh-cn.menu.main.params]
                icon = "archives" 

        [[zh-cn.menu.main]]
            identifier = "search"
            name = "搜索"
            url = "/search/"
            weight = 3
            [zh-cn.menu.main.params]
                icon = "search"

        # --- 2. 底部社交图标 (Social Menu) ---
        # 这里的关键是：[zh-cn.menu.social] 
        
        # GitHub
        [[zh-cn.menu.social]]
            identifier = "github"
            name = "GitHub"
            url = "https://github.com/Meze628"
            weight = 1
            [zh-cn.menu.social.params]
                icon = "brand-github"

        # 邮箱 (Email)
        [[zh-cn.menu.social]]
            identifier = "email"
            name = "Email"
            url = "mailto:zysmeze@gmail.com"
            weight = 2
            [zh-cn.menu.social.params]
                icon ="mail"        