# Markdown renderer configuration
[goldmark.renderer]
    unsafe = true

[goldmark.extensions.passthrough]
    enable = true

    # LaTeX math support
    # https://gohugo.io/content-management/mathematics/
    [goldmark.extensions.passthrough.delimiters]
        block  = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]

[tableOfContents]
    endLevel   = 4
    ordered    = true
    startLevel = 2

[highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    
    # 【核心修改 1】开启内联样式 (noClasses = true)
    # 只有设为 true，下面的 style 设置才会直接生效，否则 Hugo 会去读默认的 CSS 文件
    noClasses = true
    
    # 【核心修改 2】指定皮肤为 Dracula
    style = "dracula"
    
    tabWidth = 4